# Generated by Django 4.1.7 on 2023-07-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(default='TodoTitlePlaceholder', max_length=512),
        ),
    ]
